version: '3'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8000
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 4173:4173
  nginx:
    build: ./proxy
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend